import React from 'react'
import './terms.scss'
import Navbar from '../../Components/Navbar/Navbar'
import Footer from '../../Components/Footer/Footer'

const Terms = (props) => {
    return (
        <div className="Terms">
            <div className="termswrap">


                {/* navbar section */}
                {/* ********************** */}


                <div className="navwrap">
                    <Navbar
                        isLogedIn={true}
                        windowSize={props.windowSize.length > 0 && props.windowSize ? props.windowSize : undefined}
                    />
                </div>

                {/* content section  */}
                {/* *********************** */}


                <div className="termscont">
                    <div className="tuse">
                        <h1>Terms of Use</h1>
                        Effective Date: Oct. 26, 2021
                        Welcome to CREATIVE EDGE. Please read on to learn the rules and restrictions that govern your use of our website(s), products, services and applications (the “Services”). If you have any questions, comments, or concerns regarding these terms or the Services, please contact us at:
                        Email: support@steezy.co
                        Phone: (213) 394-8803
                        Address: 309 E 8th Street, #305, Los Angeles, California 90014
                        These Terms of Use (the “Terms”) are a binding contract between you and CREATIVE EDGE, INC. (“CREATIVE EDGE,” “we” and “us”). Your use of the Services in any way means that you agree to all of these Terms, and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document as well as those in the Privacy Policy. Your use of or participation in certain Services may also be subject to additional policies, rules and/or conditions (“Additional Terms”), which are incorporated herein by reference, and you understand and agree that by using or participating in any such Services, you agree to also comply with these Additional Terms.
                        Please read these Terms carefully. They cover important information about Services provided to you and any charges, taxes, and fees we bill you. These Terms include information about future changes to these Terms, automatic renewals, limitations of liability, a class action waiver and resolution of disputes by arbitration instead of in court. PLEASE NOTE THAT YOUR USE OF AND ACCESS TO OUR SERVICES ARE SUBJECT TO THE FOLLOWING TERMS; IF YOU DO NOT AGREE TO ALL OF THE FOLLOWING, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER.
                        ARBITRATION NOTICE AND CLASS ACTION WAIVER: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION AGREEMENT SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.
                    </div>
                    <div className="tchange">
                        <h2>Will these Terms ever change?</h2>
                        We are constantly trying to improve our Services, so these Terms may need to change along with our Services. We reserve the right to change the Terms at any time, but if we do, we will place a notice on our site located at https://www.steezy.co/, send you an email, and/or notify you by some other means.
                        If you don’t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes.
                        Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.
                    </div>
                    <div className="tabout">
                        <h2>What about my privacy?</h2>
                        CREATIVE EDGE takes the privacy of its users very seriously. For the current CREATIVE EDGE Privacy Policy, please click here.

                        Children’s Online Privacy Protection Act

                        The Children’s Online Privacy Protection Act (“COPPA”) requires that online service providers obtain parental consent before they knowingly collect personally identifiable information online from children who are under 13 years of age. We do not knowingly collect or solicit personally identifiable information from children under 16 years of age; if you are a child under 16 years of age, please do not attempt to register for or otherwise use the Services or send us any personal information. If we learn we have collected personal information from a child under 16 years of age, we will delete that information as quickly as possible. If you believe that a child under 16 years of age may have provided us personal information, please contact us at support@steezy.co.
                    </div>
                    <div className="tbasicuse">
                        <h2>What are the basics of using CREATIVE EDGE?</h2>
                        You may be required to sign up for an account, select a password and provide us with your email address (“CREATIVE EDGE User ID”), and other information or data, such as your other contact information. You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your CREATIVE EDGE User ID a name that you do not have the right to use, or another person’s name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission.

                        Additionally, you may be able to access certain parts or features of the Services by using your account credentials from other services (each, a “Third Party Account”), such as those offered by Google, Facebook and Apple. By using the Services through a Third Party Account, you permit us to access certain information from such account for use by the Services. You are ultimately in control of how much information is accessible to us and may exercise such control by adjusting your privacy settings on your Third Party Account.

                        You represent and warrant that you are an individual of legal age to form a binding contract (or if not, you’ve received your parent’s or guardian’s permission to use the Services and have gotten your parent or guardian to agree to these Terms on your behalf).

                        You will only use the Services for your own internal, personal, non-commercial use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws, then you aren’t authorized to use the Services. We can’t and won’t be responsible for your using the Services in a way that breaks the law.

                        You will not share your CREATIVE EDGE User ID, account or password with anyone, and you must protect the security of your CREATIVE EDGE User ID, account, password and any other access tools or credentials. You’re responsible for any activity associated with your CREATIVE EDGE User ID and account.

                        No Medical Advice; Not for Emergencies

                        CREATIVE EDGE offers dance learning tools for informational purposes only. CREATIVE EDGE does not offer medical advice or diagnoses, or engage in the practice of medicine. Our Services are not intended to be a substitute for professional medical advice, diagnosis, or treatment and are offered for informational and communicative purposes only. The Services are not intended to be, and must not be taken to be, the practice of medicine, nursing, pharmacy or other healthcare advice by CREATIVE EDGE.

                        The Services are not meant to diagnose or treat any conditions – only your medical professional can determine the right course of treatment for you and determine what is safe, appropriate and effective based on your needs. You should consult your physician before beginning to use our Services as a new fitness program. Reliance on any information provided by CREATIVE EDGE or in connection with the Services is solely at your own risk. You are solely responsible for any decisions or actions you take based on the information and materials available through the Services. Developments in medical research may impact the health, fitness or nutritional advice that may appear on the Services. No assurance can be given that the advice contained in the Services will include accurate or up to date findings or developments.

                        You acknowledge that although some Content (defined below) may be provided by individuals in the medical profession, the provision of such Content does not create a medical professional/patient relationship between you and CREATIVE EDGE or between you and any other individual or entity, and does not constitute an opinion, medical advice, or diagnosis or treatment. Healthcare providers and patients should always obtain applicable diagnostic information from appropriate trusted sources. You should never delay, avoid or disregard professional medical advice because of something you have seen or read in connection with our Services.

                        Medical Disclaimer. In using the Services, you affirm that either (A) all of the following statements are true: (i) no physician has ever informed you that you have a heart condition or that you should only do physical activities recommended by a physician; (ii) you have never felt chest pain when engaging in physical activity; (iii) you have not experienced chest pain when not engaged in physical activity at any time within the past month; (iv) you have never lost your balance because of dizziness and you have never lost consciousness; (v) you do not have a bone or joint problem that could be made worse by a change in your physical activity; (vi) your physician is not currently prescribing drugs for your blood pressure or heart condition; (vii) you do not have a history of high blood pressure, and no one in your immediate family has a history of high blood pressure or heart problems; and (viii) you do not know of any other reason you should not exercise; or (B) your physician has specifically approved of your use of the Services. If applicable, you further affirm that (1) you are not pregnant, breastfeeding or lactating; or (2) your physician has specifically approved your use of the Services. CREATIVE EDGE reserves the right to refuse or cancel your membership if we determine that you have certain medical conditions or that the representations set forth above are untrue in any respect.


                        THE SERVICES SHOULD NEVER BE USED AS A SUBSTITUTE FOR EMERGENCY CARE. IF YOU HAVE A MEDICAL OR MENTAL HEALTH EMERGENCY, ARE THINKING ABOUT SUICIDE OR TAKING ACTIONS THAT MAY CAUSE HARM TO YOU OR TO OTHERS, YOU SHOULD SEEK EMERGENCY TREATMENT AT THE NEAREST EMERGENCY ROOM OR DIAL 911.
                    </div>
                    <div className="tmessage">
                        <h2>What about messaging?</h2>
                        As part of the Services, you may receive communications through the Services, including messages that CREATIVE EDGE sends you (for example, via email). When signing up for the Services, you will receive a welcome message and instructions on how to stop receiving messages.
                    </div>
                    <div className="tservices">
                        <h2>Are there restrictions in how I can use the Services?</h2>
                        You represent, warrant, and agree that you will not provide or contribute anything, including any Content (as that term is defined below), to the Services, or otherwise use or interact with the Services, in a manner that:

                        infringes or violates the intellectual property rights or any other rights of anyone else (including CREATIVE EDGE);
                        violates any law or regulation, including, without limitation, any applicable export control laws, privacy laws or any other purpose not reasonably intended by CREATIVE EDGE;
                        is dangerous, harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;
                        jeopardizes the security of your CREATIVE EDGE User ID, account or anyone else’s (such as allowing someone else to log in to the Services as you);
                        attempts, in any manner, to obtain the password, account, or other security information from any other user;
                        violates the security of any computer network, or cracks any passwords or security encryption codes;
                        runs Maillist, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services’ infrastructure);
                        “crawls,” “scrapes,” or “spiders” any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);
                        copies or stores any significant portion of the Content; or
                        decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.
                        A violation of any of the foregoing is grounds for termination of your right to use or access the Services.
                    </div>
                    <div className="tmyrights">
                        <h2>What are my rights in the Services?</h2>
                        The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, videos, illustrations and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell, commercialize or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else’s (including CREATIVE EDGE's) rights.

                        Subject to these Terms, we grant each user of the Services a worldwide, non-exclusive, non-sublicensable and non-transferable license to use (i.e., to download and display locally) Content solely for purposes of using the Services. Use, reproduction, modification, distribution or storage of any Content for any purpose other than using the Services is expressly prohibited without prior written permission from us. You understand that CREATIVE EDGE owns the Services. You won’t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services. The Services may allow you to copy or download certain Content, but please remember that even where these functionalities exist, all the restrictions in this section still apply.
                    </div>
                    <div className="trespo">
                        <h2> Who is responsible for what I see and do on the Services?</h2>
                        Any information or Content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such Content originated, and you access all such information and Content at your own risk, and we aren’t liable for any errors or omissions in that information or Content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can’t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services.

                        You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it.

                        The Services may contain links or connections to third-party websites or services that are not owned or controlled by CREATIVE EDGE. When you access third-party websites or use third-party services, you accept that there are risks in doing so, and that CREATIVE EDGE is not responsible for such risks.

                        CREATIVE EDGE has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third-party websites or by any third party that you interact with through the Services. In addition, CREATIVE EDGE will not and cannot monitor, verify, censor or edit the content of any third-party site or service. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third-party website or service that you visit or utilize. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third-party website or service.

                        Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that CREATIVE EDGE shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.

                        If there is a dispute between participants on this site or Services, or between users and any third party, you agree that CREATIVE EDGE is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release CREATIVE EDGE, its directors, officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. You shall and hereby do waive California Civil Code Section 1542 or any similar law of any jurisdiction, which says in substance: “A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party.”


                    </div>
                    <div className="tchange">
                        <h2>Will CREATIVE EDGE ever change the Services?</h2>
                        We’re always trying to improve our Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We’ll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn’t always practical. We reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.
                    </div>
                    <div className="tanything">
                        <h2> Do the Services cost anything?</h2>
                        The Services may be free or we may charge a fee for using the Services. If you are using a free version of the Services, we will notify you before any Services you are then using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services.

                        <h3>Paid Services.</h3> Certain aspects of our Services may be subject to payments now or in the future (the “Paid Services”). Please see our Pricing page for a description of the current Paid Services. Please note that any payment terms presented to you in the process of using or signing up for a Paid Service are deemed part of these Terms. For example, some Paid Services will charge a fee for downloading or installing the Services through the App Store (as defined below) linked to your specific device. You agree to comply with, and your license to use our mobile application is conditioned upon your compliance with, such App Store terms and conditions.  Any refunds relating to the applications or inquiries regarding refunds relating to the applications shall be handled solely by the applicable App Store in accordance with such App Store’s terms and conditions.
                        <h3>Billing.</h3> We use third-party payment processors (“Payment Processors”) to bill you through a payment account linked to your account on the Services (your “Billing Account”) for use of the Paid Services. The processing of payments will be subject to the terms, conditions and privacy policies of the Payment Processor in addition to these Terms. Currently, we use Braintree (offered by PayPal, Inc.) and Stripe, Inc. as our Payment Processors. You can access Braintree’s Services Agreement and Privacy Policy at https://www.braintreepayments.com/legal and Stripe’s Terms of Service at https://stripe.com/us/checkout/legal and their Privacy Policy at https://stripe.com/us/privacy. We are not responsible for any error by, or other acts or omissions of, the Payment Processor. By choosing to use Paid Services, you agree to pay us, through the Payment Processor, all charges at the prices then in effect for any use of such Paid Services in accordance with the applicable payment terms, and you authorize us, through the Payment Processor, to charge your chosen payment provider (your “Payment Method”). You agree to make payment using that selected Payment Method. We reserve the right to correct any errors or mistakes that the Payment Processor makes even if it has already requested or received payment.
                        <h3>Payment Method.</h3> The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer or other provider of your chosen Payment Method. If we, through the Payment Processor, do not receive payment from you, you agree to pay all amounts due on your Billing Account upon demand.
                        <h3>Recurring Billing.</h3> Some of the Paid Services may consist of an initial period, for which there is a one-time charge, followed by recurring period charges as agreed to by you. By choosing a recurring payment plan, you acknowledge that such Services have an initial and recurring payment feature and you accept responsibility for all recurring charges prior to cancellation. WE MAY SUBMIT PERIODIC CHARGES (E.G., MONTHLY OR ANNUALLY) WITHOUT FURTHER AUTHORIZATION FROM YOU, UNTIL YOU PROVIDE PRIOR NOTICE (RECEIPT OF WHICH IS CONFIRMED BY US) THAT YOU HAVE TERMINATED THIS AUTHORIZATION OR WISH TO CHANGE YOUR PAYMENT METHOD. SUCH NOTICE WILL NOT AFFECT CHARGES SUBMITTED BEFORE WE REASONABLY COULD ACT. TO TERMINATE YOUR AUTHORIZATION OR CHANGE YOUR PAYMENT METHOD, GO TO ACCOUNT SETTINGS.
                        <h3>Current Information Required.</h3> YOU MUST PROVIDE CURRENT, COMPLETE AND ACCURATE INFORMATION FOR YOUR BILLING ACCOUNT. YOU MUST PROMPTLY UPDATE ALL INFORMATION TO KEEP YOUR BILLING ACCOUNT CURRENT, COMPLETE AND ACCURATE (SUCH AS A CHANGE IN BILLING ADDRESS, CREDIT CARD NUMBER, OR CREDIT CARD EXPIRATION DATE), AND YOU MUST PROMPTLY NOTIFY US OR OUR PAYMENT PROCESSOR IF YOUR PAYMENT METHOD IS CANCELED (E.G., FOR LOSS OR THEFT) OR IF YOU BECOME AWARE OF A POTENTIAL BREACH OF SECURITY, SUCH AS THE UNAUTHORIZED DISCLOSURE OR USE OF YOUR USER NAME OR PASSWORD. CHANGES TO SUCH INFORMATION CAN BE MADE AT ACCOUNT SETTINGS. IF YOU FAIL TO PROVIDE ANY OF THE FOREGOING INFORMATION, YOU AGREE THAT WE MAY CONTINUE CHARGING YOU FOR ANY USE OF PAID SERVICES UNDER YOUR BILLING ACCOUNT UNLESS YOU HAVE TERMINATED YOUR PAID SERVICES AS SET FORTH ABOVE.
                        <h3>Change in Amount Authorized.</h3> If the amount to be charged to your Billing Account varies from the amount you preauthorized (other than due to the imposition or change in the amount of state sales taxes), you have the right to receive, and we shall provide, notice of the amount to be charged and the date of the charge before the scheduled date of the transaction. Any agreement you have with your payment provider will govern your use of your Payment Method. You agree that we may accumulate charges incurred and submit them as one or more aggregate charges during or at the end of each billing cycle.
                        <h3>Auto-Renewal for Paid Services.</h3> Unless you opt out of auto-renewal, which can be done through your account settings or by contacting us at support@steezy.co, any Paid Services you have signed up for will be automatically extended for successive renewal periods of the same duration as the subscription term originally selected, at the then-current non-promotional rate. To change or resign your Paid Services at any time, go to account settings, contact us at support@steezy.co, or, for mobile applications, cancel your subscription in the subscription management section of the applicable App Store.  If you terminate a Paid Service, you may use your subscription until the end of your then-current term, and your subscription will not be renewed after your then-current term expires. However, you will not be eligible for a prorated refund of any portion of the subscription fee paid for the then-current subscription period. IF YOU DO NOT WANT TO CONTINUE TO BE CHARGED ON A RECURRING MONTHLY BASIS, YOU MUST CANCEL THE APPLICABLE PAID SERVICE THROUGH YOUR ACCOUNT SETTINGS OR TERMINATE YOUR CREATIVE EDGE ACCOUNT BEFORE THE END OF THE RECURRING TERM. PAID SERVICES CANNOT BE TERMINATED BEFORE THE END OF THE PERIOD FOR WHICH YOU HAVE ALREADY PAID, AND EXCEPT AS EXPRESSLY PROVIDED IN THESE TERMS, CREATIVE EDGE WILL NOT REFUND ANY FEES THAT YOU HAVE ALREADY PAID.
                        <h3>Reaffirmation of Authorization.</h3> Your non-termination or continued use of a Paid Service reaffirms that we are authorized to charge your Payment Method for that Paid Service. We may submit those charges for payment and you will be responsible for such charges. This does not waive our right to seek payment directly from you. Your charges may be payable in advance, in arrears, per usage, or as otherwise described when you initially selected to use the Paid Service.
                        <h3>Free Trials and Other Promotions.</h3> Any free trial or other promotion that provides access to a Paid Service must be used within the specified time of the trial. You must stop using a Paid Service before the end of the trial period in order to avoid being charged for that Paid Service. If you cancel prior to the end of the trial period and are inadvertently charged for a Paid Service, please contact us at support@steezy.co.
                    </div>
                    <div className="tstop">
                        <h2>What if I want to stop using the Services?</h2>
                        You’re free to do that at any time by contacting us at support@steezy.co; please refer to our Privacy Policy, as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services.

                        CREATIVE EDGE is also free to terminate (or suspend access to) your use of the Services or your account for any reason in our discretion, including your breach of these Terms. CREATIVE EDGE has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.

                        Account termination may result in destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account.

                        If you have deleted your account by mistake, contact us immediately at support@steezy.co – we will try to help, but unfortunately, we can’t promise that we can recover or restore anything.

                        Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us, including without limitation the arbitration agreement.
                    </div>
                    <div className="tpurchace">
                        <h2> What about Mobile Applications and In-App Purchases?</h2>
                        You acknowledge and agree that the availability of our mobile application is dependent on the third party stores from which you download the application, e.g., the App Store from Apple or the Android app market from Google (each an “App Store”). Each App Store may have its own terms and conditions to which you must agree before downloading mobile applications from such store, including the specific terms relating to Apple App Store set forth below. You agree to comply with, and your license to use our application is conditioned upon your compliance with, such App Store terms and conditions. To the extent such other terms and conditions from such App Store are less restrictive than, or otherwise conflict with, the terms and conditions of these Terms of Use, the more restrictive or conflicting terms and conditions in these Terms of Use apply.

                        Through our mobile applications, you may purchase (“In-App Purchase”) certain goods or features designed to enhance the performance of the Services. When you make an In-App Purchase, you are doing so through either the Apple iTunes service or the Google Play service and you are agreeing to their respective Terms and Conditions, available at http://www.apple.com/legal/internet-services/itunes/us/terms.html and http://play.google.com/intl/en_us/about/play-terms.html). CREATIVE EDGE is not a party to any In-App Purchase.
                    </div>
                    <div className="tknow">
                        <h2>I use the CREATIVE EDGE App available via the Apple App Store – should I know anything about that?</h2>
                        These Terms apply to your use of all the Services, including our iOS applications (the “Application”) available via the Apple, Inc. (“Apple”) App Store, but the following additional terms also apply to the Application:

                        Both you and CREATIVE EDGE acknowledge that the Terms are concluded between you and CREATIVE EDGE only, and not with Apple, and that Apple is not responsible for the Application or the Content;
                        The Application is licensed to you on a limited, non-exclusive, non-transferrable, non-sublicensable basis, solely to be used in connection with the Services for your private, personal, non-commercial use, subject to all the terms and conditions of these Terms as they are applicable to the Services;
                        You will only use the Application in connection with an Apple device that you own or control;
                        You acknowledge and agree that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the Application;
                        In the event of any failure of the Application to conform to any applicable warranty, including those implied by law, you may notify Apple of such failure; upon notification, Apple’s sole warranty obligation to you will be to refund to you the purchase price, if any, of the Application;
                        You acknowledge and agree that CREATIVE EDGE, and not Apple, is responsible for addressing any claims you or any third party may have in relation to the Application;
                        You acknowledge and agree that, in the event of any third-party claim that the Application or your possession and use of the Application infringes that third party’s intellectual property rights, CREATIVE EDGE, and not Apple, will be responsible for the investigation, defense, settlement and discharge of any such infringement claim;
                        You represent and warrant that you are not located in a country subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country, and that you are not listed on any U.S. Government list of prohibited or restricted parties;
                        Both you and CREATIVE EDGE acknowledge and agree that, in your use of the Application, you will comply with any applicable third-party terms of agreement which may affect or be affected by such use; and
                        Both you and CREATIVE EDGE acknowledge and agree that Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third-party beneficiary hereof.

                    </div>
                    <div className="trefer">
                        <h2>Can I refer other users?</h2>
                        From time to time CREATIVE EDGE may offer rewards or incentives for referring others to the Services. For details of any current referral offers, please see our referral page. The referring user (“Referrer”) may refer individuals who are neither current customers of CREATIVE EDGE nor registered users of the Services (“Referee”). A registered user is a person that already has an existing account with CREATIVE EDGE. Referrer will receive the stated reward or incentive for each Referee sent by the Referrer that completes the required action described in that specific offer (such as signing up for an account or making a purchase). All Referees must be first-time recipients of the offer, and multiple referrals to the same individual or entity will be disregarded. CREATIVE EDGE reserves the right to modify or terminate any special offers at any time and to revoke from Referrer and Referee the special offer at CREATIVE EDGE'S discretion for any reason or for no reason whatsoever. If CREATIVE EDGE determines that Referrer or Referee is attempting to obtain unfair advantage or otherwise violate the terms or spirit of such special offer, CREATIVE EDGE reserves the right to (a) revoke any rewards or incentives issued to either Referrer or Referee and/or (b) charge the Referrer or Referee for any rewards or incentives (1) used by Referrer or Referee prior to such revocation or (2) issued by CREATIVE EDGE to any ineligible Referrer or Referee. All special offers are subject to any other terms, conditions and restrictions set forth on the Services or presented in connection with the special offer.
                    </div>
                    <div className="tneed">
                        <h2>What else do I need to know?</h2>
                        Warranty Disclaimer. CREATIVE EDGE and its licensors, suppliers, partners, parent, subsidiaries or affiliated entities, and each of their respective officers, directors, members, employees, consultants, contract employees, representatives and agents, and each of their respective successors and assigns (CREATIVE EDGE and all such parties together, the “CREATIVE EDGE Parties”) make no representations or warranties concerning the Services, including without limitation regarding any Content contained in or accessed through the Services, and the CREATIVE EDGE Parties will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services or any claims, actions, suits procedures, costs, expenses, damages or liabilities arising out of use of, or in any way related to your participation in, the Services. The CREATIVE EDGE Parties make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through or in connection with the Services. THE SERVICES AND CONTENT ARE PROVIDED BY CREATIVE EDGE (AND ITS LICENSORS AND SUPPLIERS) ON AN “AS-IS” BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.

                        Limitation of Liability. TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL ANY OF THE CREATIVE EDGE PARTIES BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, BUSINESS INTERRUPTION, LOSS OF DATA, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, (B) ANY SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY, (C) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) ONE-HUNDRED ($100) DOLLARS OR (II) THE AMOUNTS PAID AND/OR PAYABLE BY YOU TO CREATIVE EDGE IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM OR (D) ANY MATTER BEYOND OUR REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL OR CERTAIN OTHER DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.

                        Indemnity. You agree to indemnify and hold the CREATIVE EDGE Parties harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys’ fees) arising from or in any way related to any claims relating to (a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of these Terms. In the event of such a claim, suit, or action (“Claim”), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder).

                        Assignment. You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without CREATIVE EDGE'S prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.

                        Choice of Law. These Terms are governed by and will be construed under the Federal Arbitration Act, applicable federal law, and the laws of the State of California, without regard to the conflicts of laws provisions thereof.

                        Arbitration Agreement. Please read the following ARBITRATION AGREEMENT carefully because it requires you to arbitrate certain disputes and claims with CREATIVE EDGE and limits the manner in which you can seek relief from CREATIVE EDGE. Both you and CREATIVE EDGE acknowledge and agree that for the purposes of any dispute arising out of or relating to the subject matter of these Terms, CREATIVE EDGE'S officers, directors, employees and independent contractors (“Personnel”) are third-party beneficiaries of these Terms, and that upon your acceptance of these Terms, Personnel will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third-party beneficiary hereof.

                        (a) Arbitration Rules; Applicability of Arbitration Agreement. The parties shall use their best efforts to settle any dispute, claim, question, or disagreement arising out of or relating to the subject matter of these Terms directly through good-faith negotiations, which shall be a precondition to either party initiating arbitration. If such negotiations do not resolve the dispute, it shall be finally settled by binding arbitration in Los Angeles County, California. The arbitration will proceed in the English language, in accordance with the JAMS Streamlined Arbitration Rules and Procedures (the “Rules”) then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes. The arbitrator shall be selected from the appropriate list of JAMS arbitrators in accordance with such Rules. Judgment upon the award rendered by such arbitrator may be entered in any court of competent jurisdiction.

                        (b) Costs of Arbitration. The Rules will govern payment of all arbitration fees. CREATIVE EDGE will pay all arbitration fees for claims less than seventy-five thousand ($75,000) dollars. CREATIVE EDGE will not seek its attorneys’ fees and costs in arbitration unless the arbitrator determines that your claim is frivolous.

                        (c) Small Claims Court; Infringement. Either you or CREATIVE EDGE may assert claims, if they qualify, in small claims court in Los Angeles County, California or any United States county where you live or work. Furthermore, notwithstanding the foregoing obligation to arbitrate disputes, each party shall have the right to pursue injunctive or other equitable relief at any time, from any court of competent jurisdiction, to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents or other intellectual property rights.

                        (d) Waiver of Jury Trial. YOU AND CREATIVE EDGE WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR JURY. You and CREATIVE EDGE are instead choosing to have claims and disputes resolved by arbitration. Arbitration procedures are typically more limited, more efficient, and less costly than rules applicable in court and are subject to very limited review by a court. In any litigation between you and CREATIVE EDGE over whether to vacate or enforce an arbitration award, YOU AND CREATIVE EDGE WAIVE ALL RIGHTS TO A JURY TRIAL, and elect instead to have the dispute be resolved by a judge.

                        (e) Waiver of Class or Consolidated Actions. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS. CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If however, this waiver of class or consolidated actions is deemed invalid or unenforceable, neither you nor CREATIVE EDGE is entitled to arbitration; instead all claims and disputes will be resolved in a court as set forth in (g) below.

                        (f) Opt-out. You have the right to opt out of the provisions of this Section by sending written notice of your decision to opt out to the following address: 309 E 8th Street, #305, Los Angeles, California 90014 postmarked within thirty (30) days of first accepting these Terms. You must include (i) your name and residence address, (ii) the email address and/or telephone number associated with your account, and (iii) a clear statement that you want to opt out of these Terms’ arbitration agreement.

                        (g) Exclusive Venue. If you send the opt-out notice in (f), and/or in any circumstances where the foregoing arbitration agreement permits either you or CREATIVE EDGE to litigate any dispute arising out of or relating to the subject matter of these Terms in court, then the foregoing arbitration agreement will not apply to either party, and both you and CREATIVE EDGE agree that any judicial proceeding (other than small claims actions) will be brought in the state or federal courts located in, respectively, Los Angeles County, California, or the federal district in which that county falls.

                        (h) Severability. If the prohibition against class actions and other claims brought on behalf of third parties contained above is found to be unenforceable, then all of the preceding language in this Arbitration Agreement section will be null and void. This arbitration agreement will survive the termination of your relationship with CREATIVE EDGE.

                        Miscellaneous. You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that the CREATIVE EDGE may, in its sole discretion, do any of the foregoing on your behalf or for itself as it sees fit. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms are found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and CREATIVE EDGE agree that these Terms are the complete and exclusive statement of the mutual understanding between you and CREATIVE EDGE, and that these Terms supersede and cancel all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of CREATIVE EDGE, and you do not have any authority of any kind to bind CREATIVE EDGE in any respect whatsoever.

                        Except as expressly set forth in the sections above regarding the Apple Application and the arbitration agreement, you and CREATIVE EDGE agree there are no third-party beneficiaries intended under these Terms.


                    </div>
                </div>



                {/* footer section */}
                {/* ********************** */}


                <div className="footer">
                    <Footer
                        windowSize={props.windowSize.length > 0 && props.windowSize ? props.windowSize : undefined}
                    />
                </div>

                
            </div>
        </div>
    )
}

export default Terms